# Site settings
title: raulpe7eira
description:
  en: 'Passionate coder, and cycling enthusiast, who loves being with the family'
  pt_BR: 'Programador apaixonado, e ciclista entusiasta, que ama estar com a família'
headline:
  en: 'Passionate coder, and cycling enthusiast, who loves being with the family'
  pt_BR: 'Programador apaixonado, e ciclista entusiasta, que ama estar com a família'
url: 'https://raulpe7eira.tech'
baseurl: ''
google_analytics: 'G-4QXLD8YPLP'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'raulpe7eira'
  email: raul.pereira@gmail.com
  with_blog: false
  # twitter_username: raulpe7eira
  # facebook_username: raulpe7eira
  instagram_username: raulpe7eira
  strava_username: raulpe7eira
  github_username:  raulpe7eira
  linkedin_username:  raulpe7eira

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: docs
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

languages: ['en', 'pt_BR']
default_lang: 'en'
exclude_from_localization: ['css', 'fonts', 'images', 'js']
parallel_localization: true
data_dir: /_data
languages_display:
  en:
    label: 'English'
    title: 'Translate to English'
  pt_BR:
    label: 'Português (BR)'
    title: 'Traduzir para Português (BR)'
dates_format:
  en: '%m/%d/%Y'
  pt_BR: '%d/%m/%Y'

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-polyglot', 'jekyll-paginate']
exclude: [vendor, 'README.md', 'Gemfile', 'Gemfile.lock', 'index_sample.html']
